version: "3.7"

services:
  cernerConnector:


    image: dhf0820/cerner_connector:240410.3    

    ports:
      - "0.0.0.0:20103:9200"
    environment:
      LISTEN_PORT: 9200
      CONFIG_ADDRESS: "http://uc_core:9200/api/rest/v1" #"http://dev.vertisoft.com:30300/api/rest/v1"
      SERVICE_NAME: "cerner_conn"
      SERVICE_VERSION: "docker_test"
      COMPANY: "test"
      REFRESH_SECRET: "Debbie loves me more"
      ACCESS_SECRET: "I am so blessed Debbie loves me!"
      USE_CACHE: "TRUE"
      API: "RESTFUL"
      DBNAME: "test"
      PAGE_SIZE: 25
    networks:
      - vs_web
      - uc_attachable
    volumes:
      - "cerner_data:/data" 
volumes:
  cerner_data:
networks:
  vs_web:
  uc_attachable:
    external: true
